import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = "https://vkzxknpveoghhccgwaan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_N2Hxy1FWrPCbUz6ifyQx6w_fqpWal1l";
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const UI_KEY = "english-study-ui-v2";
const categories = { speaking:{label:"Speaking",icon:"🎙️",description:"話す練習を、自分のテーマごとに整理できます。"}, listening:{label:"Listening",icon:"🎧",description:"聞き取り練習を、自分のテーマごとに整理できます。"}, writing:{label:"Writing",icon:"✍️",description:"英作文・日記・添削用のタブを整理できます。"}, reading:{label:"Reading",icon:"📖",description:"英文読解・記事・教材をテーマごとに整理できます。"} };
const defaultNames={speaking:"My Speaking",listening:"My Listening",writing:"My Writing",reading:"My Reading"};
let state={tabs:{speaking:[],listening:[],writing:[],reading:[]},activeCategory:"speaking",activeSubTabs:{}};let reviewState=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function escapeHtml(v=""){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function showDialog(id){const e=$("#"+id);if(e&&!e.open)e.showModal();}function closeDialog(id){const e=$("#"+id);if(e?.open)e.close();}
function saveUi(){localStorage.setItem(UI_KEY,JSON.stringify({activeCategory:state.activeCategory,activeSubTabs:state.activeSubTabs}));}
function restoreUi(){try{const x=JSON.parse(localStorage.getItem(UI_KEY));if(x){state.activeCategory=x.activeCategory||"speaking";state.activeSubTabs=x.activeSubTabs||{};}}catch{}}
function categoryTabs(){return state.tabs[state.activeCategory];}function activeSubTab(){const t=categoryTabs();return t.find(x=>x.id===state.activeSubTabs[state.activeCategory])||t[0];}
function showError(e){console.error(e);alert(`保存に失敗しました。\n${e.message||e}`);}
async function ensureDefaultTabs(){for(const category of Object.keys(categories)){const {data,error}=await supabase.from("study_tabs").select("id,name,category,created_at").eq("category",category).order("created_at");if(error)throw error;if(!data?.length){const {data:created,error:ie}=await supabase.from("study_tabs").insert({category,name:defaultNames[category]}).select("id,name,category,created_at").single();if(ie)throw ie;state.tabs[category]=[created];}else state.tabs[category]=data;if(category==="reading")state.tabs[category].forEach(t=>t.articles=[]);}}
async function loadCloudData(){state.tabs={speaking:[],listening:[],writing:[],reading:[]};await ensureDefaultTabs();const {data:articles,error:ae}=await supabase.from("reading_articles").select("id,tab_id,title,url,memo,article_date,created_at").order("created_at",{ascending:false});if(ae)throw ae;const {data:items,error:ie}=await supabase.from("learning_items").select("id,article_id,term,meaning,how,example,level,last_reviewed,created_at").order("created_at");if(ie)throw ie;const map=new Map((articles||[]).map(a=>[a.id,{id:a.id,title:a.title,url:a.url||"",memo:a.memo||"",date:a.article_date||"",items:[]}]));(items||[]).forEach(x=>map.get(x.article_id)?.items.push({id:x.id,term:x.term,meaning:x.meaning,how:x.how||"",example:x.example||"",level:x.level||0,lastReviewed:x.last_reviewed}));state.tabs.reading.forEach(t=>t.articles=(articles||[]).filter(a=>a.tab_id===t.id).map(a=>map.get(a.id)).filter(Boolean));restoreUi();for(const k of Object.keys(categories)){state.activeSubTabs[k] ||= state.tabs[k][0]?.id;if(!state.tabs[k].some(t=>t.id===state.activeSubTabs[k]))state.activeSubTabs[k]=state.tabs[k][0]?.id;}render();}
function renderMainTabs(){$$(".main-tab").forEach(b=>b.classList.toggle("active",b.dataset.mainTab===state.activeCategory));}
function renderSubTabs(){const c=$("#subTabs");c.innerHTML="";const tabs=categoryTabs(),active=state.activeSubTabs[state.activeCategory];tabs.forEach(tab=>{const b=document.createElement("button");b.className=`sub-tab${tab.id===active?" active":""}`;b.type="button";b.innerHTML=`<span>${escapeHtml(tab.name)}</span>`;if(tabs.length>1){const x=document.createElement("button");x.className="close-sub";x.type="button";x.textContent="×";x.addEventListener("click",e=>{e.stopPropagation();removeSubTab(tab.id);});b.appendChild(x);}b.addEventListener("click",()=>{state.activeSubTabs[state.activeCategory]=tab.id;saveUi();render();});c.appendChild(b);});}
function renderGeneric(){const c=categories[state.activeCategory],t=activeSubTab();$("#workspaceKicker").textContent=c.label.toUpperCase();$("#workspaceTitle").textContent=c.label;$("#contentIcon").textContent=c.icon;$("#contentTitle").textContent=`${t.name} を始めよう`;$ ("#contentDescription").textContent=c.description;}
function renderReading(){const r=state.activeCategory==="reading";$("#genericContent").classList.toggle("hidden",r);$("#readingContent").classList.toggle("hidden",!r);$("#newArticleHeaderButton").classList.toggle("hidden",!r);if(!r)return;const t=activeSubTab(),articles=t.articles||[];$("#readingTabTitle").textContent=t.name;const list=$("#articleList");list.innerHTML="";$("#readingEmpty").classList.toggle("hidden",articles.length>0);articles.forEach(a=>{const n=a.items?.length||0,card=document.createElement("article");card.className="article-card";card.innerHTML=`<div class="article-card-top"><div><span class="article-date">${escapeHtml(a.date)}</span><h4>${escapeHtml(a.title)}</h4><p>${escapeHtml(a.memo)}</p></div><span class="article-count">${n} items</span></div><div class="article-actions">${a.url?`<a class="secondary-button link-button" href="${escapeHtml(a.url)}" target="_blank" rel="noopener">記事を読む ↗</a>`:""}<button class="secondary-button" data-items="${a.id}">＋ 覚えるものを追加</button>${n?`<button class="new-button" data-review="${a.id}">▶ 復習 ${n}件</button>`:""}</div>${n?`<div class="item-preview">${a.items.slice(0,3).map(x=>`<span><strong>${escapeHtml(x.term)}</strong> · ${escapeHtml(x.meaning)}</span>`).join("")}${n>3?`<span>＋ ${n-3} more</span>`:""}</div>`:""}`;list.appendChild(card);});}
function render(){renderMainTabs();renderSubTabs();renderGeneric();renderReading();$("#tabCount").textContent=Object.values(state.tabs).reduce((n,t)=>n+t.length,0);$("#studyMinutes").innerHTML=`${totalItems()} <small>items</small>`;}function totalItems(){return state.tabs.reading.reduce((n,t)=>n+(t.articles||[]).reduce((m,a)=>m+(a.items?.length||0),0),0);}
async function addSubTab(){const c=state.activeCategory,name=window.prompt(`${categories[c].label} に追加するタブ名を入力してください`,c==="reading"?"BBC News":"New lesson");if(!name?.trim())return;const {data,error}=await supabase.from("study_tabs").insert({category:c,name:name.trim()}).select("id,name,category,created_at").single();if(error)return showError(error);data.articles=c==="reading"?[]:undefined;state.tabs[c].push(data);state.activeSubTabs[c]=data.id;saveUi();render();}
async function removeSubTab(id){const c=state.activeCategory,t=categoryTabs(),i=t.findIndex(x=>x.id===id);if(i<0||t.length<=1)return;if(!confirm(`「${t[i].name}」を削除しますか？`))return;const {error}=await supabase.from("study_tabs").delete().eq("id",id);if(error)return showError(error);t.splice(i,1);state.activeSubTabs[c]=t[Math.max(0,i-1)].id;saveUi();render();}
async function saveArticle(e){e.preventDefault();const t=activeSubTab(),payload={tab_id:t.id,title:$("#articleTitle").value.trim(),url:$("#articleUrl").value.trim()||null,memo:$("#articleMemo").value.trim()||null};const {data,error}=await supabase.from("reading_articles").insert(payload).select("id,tab_id,title,url,memo,article_date,created_at").single();if(error)return showError(error);t.articles||=[];t.articles.unshift({id:data.id,title:data.title,url:data.url||"",memo:data.memo||"",date:data.article_date,items:[]});closeDialog("articleDialog");render();}
function parseItems(text){const t=text.trim();if(t.startsWith("[")){try{return JSON.parse(t).map(x=>({term:x.term||x.word||x.expression||"",meaning:x.meaning||"",how:x.how||x.memory||x.mnemonic||"",example:x.example||""})).filter(x=>x.term&&x.meaning);}catch{}}return text.split(/\n+/).map(l=>l.trim()).filter(Boolean).map(l=>{const p=l.split(/\t|\s{2,}|\s*\/\s*/).map(x=>x.trim());return{term:p[0]||"",meaning:p[1]||"",how:p[2]||"",example:p[3]||""};}).filter(x=>x.term&&x.meaning);}
function findArticle(id){return(activeSubTab()?.articles||[]).find(a=>a.id===id);}
async function saveItems(e){e.preventDefault();const a=findArticle(window.currentArticleId);if(!a)return;const items=parseItems($("#itemsInput").value);if(!items.length)return alert("読み取れるデータがありません。4列のタブ区切りで貼ってみてください。");const payload=items.map(x=>({article_id:a.id,term:x.term,meaning:x.meaning,how:x.how||null,example:x.example||null}));const {data,error}=await supabase.from("learning_items").insert(payload).select("id,article_id,term,meaning,how,example,level,last_reviewed");if(error)return showError(error);a.items.push(...data.map(x=>({id:x.id,term:x.term,meaning:x.meaning,how:x.how||"",example:x.example||"",level:x.level||0,lastReviewed:x.last_reviewed})));closeDialog("itemsDialog");render();}
function startReview(a){if(!a?.items?.length)return;reviewState={article:a,index:0,revealed:false};showDialog("reviewDialog");renderReview();}async function updateReview(item,level){const {error}=await supabase.from("learning_items").update({level,last_reviewed:new Date().toISOString()}).eq("id",item.id);if(error)return showError(error);item.level=level;}
function renderReview(){const item=reviewState.article.items[reviewState.index],total=reviewState.article.items.length,rev=reviewState.revealed;$("#reviewBody").innerHTML=`<div class="review-progress">${reviewState.index+1} / ${total}</div><div class="review-card"><p class="review-label">英語</p><h3>${escapeHtml(item.term)}</h3>${rev?`<div class="answer"><strong>${escapeHtml(item.meaning)}</strong>${item.how?`<p>🧠 ${escapeHtml(item.how)}</p>`:""}${item.example?`<p class="review-example">${escapeHtml(item.example)}</p>`:""}</div>`:`<p class="tap-hint">まず意味を思い出してみよう。</p>`}</div>${rev?`<div class="review-buttons"><button class="review-result" data-level="0">😵 忘れた</button><button class="review-result" data-level="1">😐 あやしい</button><button class="review-result good" data-level="2">😊 余裕</button></div>`:`<button class="new-button reveal-button" id="revealAnswer">答えを見る</button>`}`;$("#revealAnswer")?.addEventListener("click",()=>{reviewState.revealed=true;renderReview();});$$(".review-result").forEach(b=>b.addEventListener("click",async()=>{await updateReview(item,Number(b.dataset.level));if(reviewState.index<total-1){reviewState.index++;reviewState.revealed=false;renderReview();}else{$("#reviewBody").innerHTML=`<div class="review-finished"><div class="content-icon">🎉</div><h3>今日の復習、おつかれさま！</h3><p>${total}件を復習しました。</p><button class="new-button" data-close="reviewDialog">閉じる</button></div>`;$("[data-close=reviewDialog]").addEventListener("click",()=>closeDialog("reviewDialog"));}}));}

$("#newTabButton").addEventListener("click",addSubTab);$$(".main-tab").forEach(b=>b.addEventListener("click",()=>{state.activeCategory=b.dataset.mainTab;saveUi();render();}));$$("[data-close]").forEach(b=>b.addEventListener("click",()=>closeDialog(b.dataset.close)));$("#newArticleButton").addEventListener("click",()=>{$("#articleForm").reset();showDialog("articleDialog");$("#articleTitle").focus();});$("#newArticleHeaderButton").addEventListener("click",()=>{$("#articleForm").reset();showDialog("articleDialog");$("#articleTitle").focus();});$("#articleForm").addEventListener("submit",saveArticle);$("#articleList").addEventListener("click",e=>{const id=e.target.closest("[data-items]")?.dataset.items,r=e.target.closest("[data-review]")?.dataset.review;if(id){window.currentArticleId=id;$("#itemsInput").value="";showDialog("itemsDialog");$("#itemsInput").focus();}if(r)startReview(findArticle(r));});$("#itemsForm").addEventListener("submit",saveItems);
await loadCloudData();
